M48
; DRILL file {KiCad 9.0.1-9.0.1-0~ubuntu22.04.1} date 2025-04-23T20:29:42+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-23T20:29:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-9.0.1-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X3.9882Y-3.1154
X3.9882Y-3.3429
M30
